stages:
- build

build-docker-image:
  tags:
  - dind
  stage: build
  only:
  - commercial

  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
  - export TIME=$(date +%s)
  - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${TIME} -t ${CI_REGISTRY_IMAGE}:latest .
  - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${TIME}
  - docker push ${CI_REGISTRY_IMAGE}:latest
