version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_build:
      - sphinx-build -b html docs/en/ docs/en/_build/html
      - sphinx-build -b html docs/zh/ docs/zh/_build/html

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/en/conf.py
  fail_on_warning: false
