llm_config:
  provider: zhipuai
  api_key: <YOUR-API-KEY> # Please replace with the API key obtained from the LLM provider website.
  model: GLM-4-Flash # The name of the model to be used.

simulator_config:
  task_name: "citysim" # The name of the simulation task, affect the directory name for log output
  max_day: 1 # Defines the maximum number of days for the simulation.
  start_step: 0 # The initial step of the simulation in seconds.
  total_step: 86400 # Total steps in the simulation in seconds.
  log_dir: log # Directory where simulator logs will be stored.

redis:
  server: <REDIS-SERVER> # Specify the Redis server address here.
  port: 6379 # Port number on which the Redis service is running.
  password: <PASSWORD> # Password for Redis server authentication.

map_config:
  file_path: data/beijing_map.pb # Path to the map file, reference to step1.

metric_config:
  mlflow: 
      username: <USER-NAME> # Username for MLflow authentication.
      password: <PASSWORD> # Password for MLflow authentication.
      mlflow_uri: <MLFLOW-URI> # URI pointing to the MLflow tracking server.

pgsql:
  enabled: true # Whether PostgreSQL database integration is enabled.
  dsn: <DSN> # Data source name for connecting to PostgreSQL.

avro:
  enabled: true # Whether Avro serialization is enabled.
  path: <AVRO-PATH> # Directory path for storing cached data or serialized files.
